var tableData = null;

// Lade die Tabelle beim Laden der Seite
window.onload = function() {
  loadTable();
};

function loadTable() {
  var jsonData = [
    // JSON-Daten hier einfügen
   
  
    [
      "nid",
      "Kürzel",
      "externer kennzeichner",
      "Titel",
      "Gegenstand",
      "Art",
      "Beschreibung",
      "Erfahrungen, Informationen, Diskusionen",
      "link",
      "UN",
      "EU",
      "DE",
      "NGO",
      "einsatzdatum",
      "kaskade",
      "letzte änderung",
      "entfalldatum",
      "resulteriender status",
      "Branche",
      "Rechtsform",
      "Sitz im Inland",
      "Niederlassung",
      "MA Anzahl größer",
      "Umsatz größer",
      "Gesamtvermögen größer",
      "Verpackungen",
      "Abfälle",
      "Energieverbrauchsrelevante Produkte",
      "Kombinationen",
      "Schlagwortsuche",
      "Aktueller Stand abgelegt?",
      "Erstellt am",
      "letzte prüfung durch Community am",
      "kuebler",
      "bezug",
      "Test"
    ],
    [
      "1",
      "CSR-RUG",
      "2014/95/EU",
      "CSR-Richtlinie-Umsetzungsgesetz",
      "Gesetz",
      "Gesetz",
      "Corporate Social Responsibility (CSR) Umsetzungsrichtlinie für NFRD (2014/95/EU). Große kapitalmarktorientierte Unternehmen, Kriditinstitute und Versichtungen mit größe > Mitarbeiter und > 20 Mio. Umsatz, > 20 Mio Gesamtvermögen",
      "",
      "http://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl117s0802.pdf",
      "",
      "",
      "x",
      "",
      "2017-03-01",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bericht",
      "ja",
      "45163",
      "",
      "x",
      "Nachhaltigkeitsbericht",
      "x"
    ],
    [
      "1.1",
      "Anforderung CSR (Gesetz)",
      "2014/95/EU",
      "HGB §289 c II & III Handelsgesetzbuch\r\n§ 289c Inhalt der nichtfinanziellen Erklärung",
      "Interpretierte Anforderung",
      "Gesetz",
      "Überführung in Handelsgesetzbuch als Berichtsbestandteile (§289 c II HGB) und Berichtsumfang nach (§289 c III HGB) der NFRD (2014/95/EU) als nichtfinanzielle Erklärung (NFE). Große kapitalmarktorientierte Unternehmen, Kriditinstitute und Versichtungen mit größe > Mitarbeiter und > 20 Mio. Umsatz, > 20 Mio Gesamtvermögen",
      "",
      "https://www.gesetze-im-internet.de/hgb/HGB.pdf",
      "",
      "",
      "x",
      "",
      "2017-04-19",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bericht",
      "ja",
      "45163",
      "",
      "x",
      "Nachhaltigkeitsbericht",
      "x"
    ],
    [
      "1.2",
      "Anforderung CSR (Richtlinie)",
      "2014/95/EU",
      "Non-Financial Reporting Directive - NFRD (2014/95/EU)",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Bereits seit dem 01.01.2017 müssen große kapitalmarktorientierte Unternehmen gemäß der Non-Financial Reporting Directive - NFRD (2014/95/EU), die als (Corporate Social Responsibility) CSR-Richtlinie-Umsetzungsgesetze (CSR-RUG) am 19.04.2017 in nationales Gesetz überführt und im HGB verankert wurde, eine Nichtfinanzielle Erklärung (NFE) offenlegen. Große kapitalmarktorientierte Unternehmen, Kriditinstitute und Versichtungen mit größe > Mitarbeiter und > 20 Mio. Umsatz, > 20 Mio Gesamtvermögen",
      "",
      "https://eur-lex.europa.eu/eli/dir/2014/95",
      "",
      "x",
      "",
      "",
      "2014-10-22",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "20",
      "20",
      "",
      "",
      "",
      "",
      "Bericht",
      "ja",
      "45163",
      "",
      "x",
      "Nachhaltigkeitsbericht",
      "x"
    ],
    [
      "1.3",
      "Anforderung CSR (Verordnung)",
      "",
      "Sustainable-Finance – EU Taxonomy Regulation (EU) 2020/852 ",
      "Interpretierte Anforderung",
      "Verordnung",
      "Sustainable-Finance-Taxonomie der EU verlangt zudem, dass alle Unternehmen, die unter die europäische Berichterstattungspflicht fallen, den Anteil ihrer nach EU-Taxonomie „nachhaltig“ anzusehenden Geschäftsaktivitäten in der nicht-finanziellen Erklärung angeben müssen. Dies umschließt Umsatzerlöse, Investitionsausgaben (CAPEX) und Betriebsausgaben (OPEX) für Unternehmen der Realwirtschaft und branchenspezifische KPIs für Finanzunternehmen. Vor allem kleine und mittelständische Unternehmen (KMU) stehen damit vor der Herausforderung, sich erstmals mit der Nachhaltigkeitsberichterstattung auseinanderzusetzen. Alle 2/3 Bedingungen. Ab 250 MA oder >40 Mio Umsatz oder > 20 Mio. also allge großen Unternehmen. 1.2022 für Große KG, Ab 2023 allge große Untern.",
      "",
      "",
      "",
      "x",
      "",
      "",
      "2022-01-01",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bericht",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.4",
      "Anforderung CSR (Richtlinie)",
      "2022/2464/EU",
      "Im bericht müssen ESG- Informationen im Rahmen der Corporate Sustainability Reporting Directive (CSRD) nachgewisen werden: Umwelt, Soziales und verantwortungsvolle Unternehmensführung und veröffentlicht werden",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Im aktuellen Entwurf vorgesehen, dass ab dem Geschäftsjahr 2023 alle Unternehmen ab 250 Mitarbeitende (unabhängig von der Kapitalmarktorientierung) und einem Umsatz größer 40 Mio. € und einer Bilanzsummer größer 20 Mio. € (zwei aus drei Kriterien müssen erfüllt werden) und ab dem Geschäftsjahr 2026 kapitalmarktorientierte kleine und mittelständische Unternehmen berichtspflichtig werden. Das bedeutet, dass eine Nachhaltigkeitsberichtserstattung im Lagebericht zu veröffentlichen ist. \r\n\r\nESRS 2 General Disclosures, Strategy, Governance, Materiality\r\nESRS E1 Climate Change\r\nESRS S1 Own Workforce General Standard (ab 250 Mitarbeitenden)",
      "",
      "https://eur-lex.europa.eu/eli/dir/2022/2464",
      "",
      "x",
      "",
      "",
      "2022-12-01",
      "2024-01-01",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "250",
      "40",
      "",
      "",
      "",
      "",
      "",
      "Bericht",
      "ja",
      "45163",
      "",
      "x",
      "Nachhaltigkeitsbericht",
      "x"
    ],
    [
      "1.4.1",
      "Lösungsorientierte Anforderung CSR",
      "",
      "Verpflichtende Messung von CO2-Emissionen im Unternehmen - CSRD Beitragspflicht mit dem Co2 Rechner des Umweltbundesamtes",
      "Lösungsorientierte Anforderung",
      "",
      "",
      "",
      "https://uba.co2-rechner.de/de_DE/",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.5",
      "Anforderung CSR (Richtlinie)",
      "2022/0051/EU",
      "Nachweis im Bericht über Corporate Sustainability Due Diligence Directive (CSDDD)",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Richtlinienentwurf zur Ausweitung der Sorgfaltspflichten im Rahmen der Lieferkette (Corporate Sustainability Due Diligence Directive [CSDDD]: Vorschlag für eine RICHTLINIE DES EUROPÄISCHEN PARLAMENTS UND DES RATES über die Sorgfaltspflichten von Unternehmen im Hinblick auf Nachhaltigkeit und zur Änderung der Richtlinie (EU) 2019/1937. in Klärung aber verschärfung, plan ist 2023",
      "",
      "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022PC0071",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "geplant",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette, Bericht, Akkreditierung",
      "ja",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.6",
      "Anforderung CSR (Standard)",
      "",
      "Financial and Sustaniability Reporting Standards for EU",
      "Interpretierte Anforderung",
      "Standard",
      "Unternehmen, die zukünftig Nachhaltigkeitsberichte auf der Grundlage der CSRD erstellen müssen, legen Informationen zu den ESRS offen. EFRAG’s mission is to serve the European public interest in both financial reporting and sustainability reporting by developing and promoting European views in the field of corporate reporting and by developing draft EU Sustainability Reporting Standards.",
      "",
      "https://www.efrag.org/Activities/2010051123028442/Sustainability-reporting-standards-roadmap",
      "",
      "x",
      "",
      "x",
      "",
      "",
      "",
      "",
      "geplant",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bericht",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.7",
      "Anforderung CSR (Standard)",
      "",
      "European Sustainability Reporting Standards (ESRS)",
      "Interpretierte Anforderung",
      "Standard",
      "Deloitte 8.2022: vom Damit ist der Weg frei für eine baldige Verabschiedung sowie der Finalisierung der European Sustainability Reporting Standards (ESRS), da diese auf Vorgaben in der CSRD zurückgehen und vorsehen, dass Unternehmen künftig über Nachhaltigkeitsinformationen unter Anwendung der von EFRAG entwickelten ESRS berichten müssen. WBK 11.2022: Am 22. November 2022 hat die European Financial Reporting Advisory Group (EFRAG) die Entwürfe der zwölf European Sustainability Reporting Standards (ESRS) an die Europäische Kommission übermittelt. Nachdem der europäische Rat am 28. November 2022 endgültig grünes Licht für die Corporate Sustainability Reporting Directive (CSRD) gegeben hat, stehen die Pflichtangaben nun fest. Dazu gehören zum ersten die General Disclosures und Governance Angaben (ESRS 2), für Unternehmen ab 250 Miatarbeitenden zum zweiten der ESRS S1 Eigene Belegschaft. Zum dritten muss der EFRAG Standard ESRS E1 Klimawandel von allen CSRD-pflichtigen Unternehmen unabhängig von einer besonderen Wesentlichkeitsprüfung reportet werden.\r\n\r\nOb weitere Standards reportet werden müssen, hängt von deren Wesentlichkeit für das Unternehmen ab. Diese muss individuell geprüft werden.",
      "",
      "https://www.efrag.org/lab6?AspxAutoDetectCookieSupport=1",
      "",
      "x",
      "",
      "x",
      "",
      "",
      "",
      "",
      "geplant",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bericht",
      "ja",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.8",
      "Anforderung CSR (Standard)",
      "",
      "GRI-Standards  für offentliche Berichtserstattung als Grundlage für ESG-Kennzahlen",
      "Interpretierte Anforderung",
      "Standard",
      "Die GRI-Richtlinien sind freiwillige Richtlinien für Nachhaltigkeitsberichterstattung und bieten Unternehmen einen Rahmen für die Offenlegung von Umwelt-, sozialen und Governance-Aspekten. Ziel der GRI-Standards: Durch Standardisierung und Vergleichbarkeit, Transparenz über die CSR Aktivitäten eines Unternehmens zu schaffen. Einige Unternehmen nutzen auch den Deutschen Nachhaltigkeitskodex (DNK).",
      "",
      "https://www.globalreporting.org/",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bericht, Industriestandard",
      "ja",
      "45163",
      "",
      "x",
      "Nachhaltigkeitsbericht",
      "x"
    ],
    [
      "1.9",
      "Anforderung CSR (Standard)",
      "IRF",
      "IR – International Framework for Reporting",
      "Interpretierte Anforderung",
      "Standard",
      "Dieser Rahmen bietet Unternehmen Leitlinien für die Berichterstattung, die finanzielle und nicht-finanzielle Informationen in einem integrierten Bericht kombiniert. Das IR Framework ist ein international anerkannter Rahmen für Unternehmensberichterstattung, der von der International Integrated Reporting Council (IIRC) entwickelt wurde. Das Ziel dieses Frameworks ist es, Unternehmen dabei zu unterstützen, umfassendere und zusammenhängende Berichte zu erstellen, die nicht nur finanzielle Informationen, sondern auch Informationen über Umwelt-, soziale und Governance-Aspekte (ESG) enthalten.\r\n\r\nDas IR Framework fördert die Integration von finanziellen und nichtfinanziellen Informationen in einem einzigen Bericht, um den interessierten Parteien ein klareres Bild von der Gesamtleistung und -strategie eines Unternehmens zu vermitteln. Es soll Unternehmen dabei helfen, ihre Wertschöpfungsketten, ihre Beziehungen zu Stakeholdern, ihre Nachhaltigkeitsstrategien und ihre Auswirkungen auf die Gesellschaft und die Umwelt besser zu kommunizieren.\r\n\r\nDas Framework legt Prinzipien, Konzepte und Leitlinien fest, die Unternehmen bei der Entwicklung integrierter Berichte unterstützen. Dabei werden sowohl finanzielle als auch nichtfinanzielle Aspekte berücksichtigt. Es betont die Notwendigkeit, relevante Informationen in einer klaren, konzisen und verständlichen Weise zu präsentieren, um das Verständnis und das Vertrauen der Interessengruppen zu fördern.\r\n\r\nDie Anwendung des IR Frameworks kann dazu beitragen, die Transparenz und Rechenschaftspflicht von Unternehmen zu erhöhen, ihre langfristige Wertgenerierung zu fördern und ihre Auswirkungen auf die Gesellschaft und die Umwelt in den Berichten angemessen zu reflektieren.\r\n\r\n\r\n\r\n",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bericht",
      "nein",
      "45163",
      "",
      "x",
      "Nachhaltigkeitsbericht",
      "x"
    ],
    [
      "1.10",
      "Anforderung CSR (Standard)",
      "",
      "UN Global Compact",
      "Interpretierte Anforderung",
      "Standard",
      "Der UN Global Compact unterstützt Unternehmen dabei:\r\n\r\n1. Auf Grundlage der 10 Prinzipien verantwortungsvoll zu handeln.\r\n2. Innovative Lösungen zur Verwirklichung der nachhaltigen Entwicklungsziele (Sustainable Development Goals) voranzutreiben.",
      "",
      "https://unglobalcompact.org/",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.11",
      "Anforderung CSR (Standard)",
      "",
      "SASB-Standards",
      "Interpretierte Anforderung",
      "Standard",
      "Ab August 2022 übernimmt der International Sustainability Standards Board (ISSB) der IFRS Foundation die Verantwortung für die Standards des SASB. Der ISSB hat sich verpflichtet, auf den branchenbasierten SASBStandards aufzubauen und den branchenbasierten SASB-Ansatz zur Entwicklung von Standards\r\nzu berücksichtigen. Der ISSB empfiehlt Erstellern und Investoren, die SASB-Standards so lange weiterhin vollumfänglich zu unterstützen und zu verwenden, bis sie durch die IFRS Sustainability Disclosure Standards (IFRS-Standards zur Nachhaltigkeitsberichterstattung) ersetzt werden.https://navigator.sasb.org/ The IFRS Foundation’s International Sustainability Standards Board (ISSB) encourages companies to keep using SASB Standards. SASB Standards identify the subset of environmental, social, and governance issues most relevant to financial performance in each of 77 industries. They are designed to help companies disclose financially-material sustainability information to investors.\r\n\r\nSASB’s rigorous and transparent standard-setting process includes evidence-based research, broad and balanced participation from companies, investors, and subject matter experts, and oversight and approval from an independent Standards Board. Supporting materials related to the development of the standards are available in the Standard-Setting Archive.\r\n\r\nStandards are free to download for non-commercial use. If you are interested in using the Standards for commercial purposes, learn more about licensing opportunities.",
      "",
      "https://www.sasb.org/",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bilanzierung, Industriestandard",
      "ja",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.12",
      "Anforderung CSR (Standard)",
      "",
      "Environmental Social Governance-Kennzahlen",
      "Interpretierte Anforderung",
      "Standard",
      "ESG-Kennzahlen sind ein Akronym für Umwelt- (E), Sozial- (S) und Governance-Kennzahlen (G). Damit wird die Leistung eines Unternehmens anhand von Umwelt-, Sozial- und Governance-Kriterien gemessen. ",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "geplant",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Bericht",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.13",
      "Anforderung CSR (Standard)",
      "",
      "Organisation Value Balancing Alliance e.V. (VBA)",
      "Interpretierte Anforderung",
      "Standard",
      "https://www.value-balancing.com/en/our-work.html Neben regulatorischen Vorschriften bestehen zudem bereits Bestrebungen der Industrie nach einer standardisierten Methode, um mehr Nachhaltigkeit, Transparenz und Vergleichbarkeit in der Wirtschaft zu gewährleisten. Die 2019 gegründete gemeinnützige Organisation Value Balancing Alliance e.V. (VBA)3 hat sich zum Ziel gesetzt, die Art und Weise zu verändern, wie Unternehmensleistungen pragmatisch und standardisiert gemessen und bewertet werden.",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Freiwillig",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "1.14",
      "Anforderung CSR (Standard)",
      "CSR ISO 26000",
      "CSR ISO 26000 Nachhaltigkeitsmanagement",
      "Interpretierte Anforderung",
      "Standard",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "2",
      "HinSchG",
      "BGBl. 2023 I Nr. 140",
      "Hinweisgeberschutzgesetz",
      "Gesetz",
      "Gesetz",
      "",
      "",
      "https://www.gesetze-im-internet.de/hinschg/BJNR08C0B0023.html",
      "",
      "",
      "x",
      "",
      "2023-05-31",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Datenschutz, Meldewesen, Bericht",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "2.1",
      "PS (Richtlinie)",
      "2019/1937/EU",
      "Schutz von Personen, die Verstöße gegen das Unionsrecht melden",
      "Interpretierte Anforderung",
      "Richtlinie",
      "RICHTLINIE (EU) 2019/1937 DES EUROPÄISCHEN PARLAMENTS UND DES RATES vom 23. Oktober 2019 zum Schutz von Personen, die Verstöße gegen das Unionsrecht melden",
      "",
      "https://eur-lex.europa.eu/legal-content/de/ALL/?uri=CELEX:32019L1937",
      "",
      "x",
      "",
      "",
      "2019-10-23",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Datenschutz, Meldewesen, Bericht",
      "ja",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "3",
      "ElektroG",
      "",
      "Elektro- und Elektronikgerätegesetz - ElektroG",
      "Gesetz",
      "Gesetz",
      "Gesetz über das Inverkehrbringen, die Rücknahme und die umweltverträgliche Entsorgung von Elektro- und Elektronikgeräten (Elektro- und Elektronikgerätegesetz - ElektroG)",
      "",
      "https://www.gesetze-im-internet.de/elektrog_2015/",
      "",
      "",
      "x",
      "",
      "2015-10-20",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktentwicklung, Elektrik, Elektronik",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "3.1",
      "WEEE-Richtlinie (Richtlinie)",
      "2012/19/EU",
      "Elektro- und Elektronik-Altgeräte (WEEE-Richtlinie)",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/ALL/?uri=celex%3A32012L0019",
      "",
      "x",
      "",
      "",
      "2012-08-13",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktentwicklung, Elektrik, Elektronik",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "3.2",
      "RoHS-Richtlinie (Richtlinie)",
      "2011/65/EU",
      "Beschränkung der Verwendung bestimmter gefährlicher Stoffe in Elektro- und Elektronikgeräten (RoHS-Richtlinie)",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=celex%3A32011L0065",
      "",
      "x",
      "",
      "",
      "2011-07-11",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktentwicklung, Elektrik, Elektronik",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "4",
      "UAG",
      "",
      "Umweltauditgesetz - UAG",
      "Gesetz",
      "Gesetz",
      "Gesetz zur Ausführung der Verordnung (EG) Nr. 1221/2009 des Europäischen Parlaments und des Rates vom 25. November 2009 über die freiwillige Teilnahme von Organisationen an einem Gemeinschaftssystem für Umweltmanagement und Umweltbetriebsprüfung und zur Aufhebung der Verordnung (EG) Nr. 761/2001, sowie der Beschlüsse der Kommission 2001/681EG und 2006/193/EG",
      "",
      "https://www.gesetze-im-internet.de/uag/",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Umwelt, Managementsystem, Audit",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "4.1",
      "UU (Verordnung)",
      "2009/1221/EU",
      "Umweltmanagement und Umweltbetriebsprüfung",
      "Interpretierte Anforderung",
      "Verordnung",
      "VERORDNUNG (EG) Nr. 1221/2009 DES EUROPÄISCHEN PARLAMENTS UND DES RATES\r\nvom 25. November 2009\r\nüber die freiwillige Teilnahme von Organisationen an einem Gemeinschaftssystem für\r\nUmweltmanagement und Umweltbetriebsprüfung und zur Aufhebung der Verordnung (EG)\r\nNr. 761/2001, sowie der Beschlüsse der Kommission 2001/681/EG und 2006/193/EG",
      "",
      "https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2009:342:0001:0045:de:PDF",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Umwelt, Managementsystem, Audit",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "4.2",
      "Anforderungn UU (Standard)",
      "ISO14001",
      "ISO 14001 (Umweltmanagementsystem)",
      "Interpretierte Anforderung",
      "Standard",
      "Die ISO 14001 ist ein international anerkannter Standard für Umweltmanagementsysteme. Unternehmen, die nach diesem Standard zertifiziert sind, verpflichten sich zur kontinuierlichen Verbesserung ihrer Umweltleistung und zur Einhaltung umweltfreundlicher Praktiken.",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Umwelt, Managementsystem, Audit",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "4.2.1",
      "LA UU (Zertifikat)",
      "emas",
      "Ressourcensparendes Umweltmanagement mit EMAS",
      "Lösungsorientierte Anforderung",
      "Zerifikat",
      "Als freiwilliges Instrument der Europäischen Union\r\n\r\nist EMAS für alle Branchen und Betriebsgrößen offen,\r\ndeckt alle Anforderungen der DIN EN ISO 14001 ab und\r\nist weltweit anwendbar.",
      "",
      "https://www.emas.de/",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Umwelt, Managementsystem, Audit",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5",
      "Kaskade LkSG",
      "20210303DE",
      "Lieferkettensorgfalts-pflichtengesetzes (LkSG)",
      "Gesetz",
      "Gesetz",
      "1. Leiharbeiter ab einer Beschäftigung von 6 Monaten berücksichtigen. MA von konzernangehörigen Gesellschaften müssen berücksichtigt werden.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "2023-01-01",
      "2024-01-01",
      "",
      "2023-12-31",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "(Sitz und MA) oder (Niederlassung und MA)",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.1",
      "Anforderung LkSG (Richtlinie)",
      "20210303DE",
      "Festlegung einer betriebsinternen Zuständigkeit",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Öffentliche Erklärung der verantwortlichen Stelle im Unternehmen.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.2",
      "Anforderung LkSG (Richtlinie)",
      "20210303DE",
      "Einführung von Prozessen und Prozessmanagement zur Sorgfallspflicht",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Unternehmen werden ermutigt oder verpflichtet, eine \"Due Diligence\" (Sorgfaltspflicht) in ihren Lieferketten durchzuführen, um sicherzustellen, dass alle Beteiligten entlang der Kette die gleichen Standards einhalten",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.3",
      "Anforderung LkSG (Richtlinie)",
      "20210303DE",
      "Abgabe einer Grundsatzerklärung zur Menschenrechtsstrategie des Unternehmens",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Die Abgabe einer Grundsatzerklärung zur Menschenrechtsstrategie eines Unternehmens beinhaltet die schriftliche Erklärung des Unternehmens, wie es Menschenrechte in seiner Geschäftstätigkeit respektiert, schützt und fördert.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.4",
      "Anforderung LkSG (Richtlinie)",
      "20210303DE",
      "Durchführung regelmäßiger Risikoanalysen und Risikobewertungen",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Unternehmen müssen eine umfassende Risikoanalyse ihrer Lieferketten durchführen, um potenzielle Risiken in Bezug auf Menschenrechtsverletzungen, Umweltschäden und Arbeitsnormverletzungen zu identifizieren.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.4.1",
      "Lösungsorientierte Anforderung LkSG (Standard)",
      "",
      "Durchführung einer wesentlichkeitsanalyse",
      "Lösungsorientierte Anforderung",
      "Standard",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette, Wesentlichkeitsanalyse",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.5",
      "Anforderung LkSG (Richtlinie)",
      "20210303DE",
      "Verankerung von Präventionsmaßnahmen im eigenen Geschäftsbereich und gegenüber unmittelbaren Zulieferern",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Auf Grundlage der Risikoanalyse müssen Unternehmen angemessene präventive Maßnahmen ergreifen, um Menschenrechtsverletzungen und Umweltschäden entlang ihrer Lieferkette zu verhindern. Hierzu gehören die Implementierung von Verhaltenskodizes, Schulungen für Lieferanten und die Überprüfung von Arbeitsbedingungen.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.6",
      "Anforderung LkSG (Richtlinie)",
      "20210303DE",
      "Einführung eines Beschwerdemechanismus",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Unternehmen müssen Mechanismen einrichten, über die Mitarbeiter, Lieferanten oder andere Betroffene Bedenken und Beschwerden hinsichtlich Menschenrechtsverletzungen und Umweltproblemen melden können.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.6.1",
      "LA LkSG DIY (Community Idee)",
      "20210303DE",
      "Kontaktformular auf Webseite mit Excel-Dokumentation und RASI-Chart",
      "Lösungsorientierte Anforderung",
      "Community Idee",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.6.2",
      "LA LkSG WF (Community Idee)",
      "20210303DE",
      "Workflowmanagementsystem",
      "Lösungsorientierte Anforderung",
      "Community Idee",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.7",
      "Anforderung LkSG (Richtlinie)",
      "20210303DE",
      "Transparenz durch Lieferkettenbericht",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Unternehmen müssen transparent über ihre Lieferkettenpraktiken berichten, einschließlich ihrer Risikoanalysen, ergriffenen Maßnahmen und deren Wirksamkeit. Dies kann in Form von öffentlichen Berichten oder auf ihren Websites geschehen.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "Alle",
      "Deutschland",
      "Deutschland",
      "1000",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "5.8",
      "Anforderung LkSG (Richtlinie)",
      "2022/0051/EU",
      "Umsetzung geplante Corporate Sustainability Due Diligence Directive (CSDDD)",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Richtlinienentwurf zur Ausweitung der Sorgfaltspflichten im Rahmen der Lieferkette (Corporate Sustainability Due Diligence Directive [CSDDD]: Vorschlag für eine RICHTLINIE DES EUROPÄISCHEN PARLAMENTS UND DES RATES über die Sorgfaltspflichten von Unternehmen im Hinblick auf Nachhaltigkeit und zur Änderung der Richtlinie (EU) 2019/1937. in Klärung aber verschärfung, plan ist 2023",
      "",
      "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022PC0071",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "geplant",
      "Alle",
      "Kapitalgeselschaft",
      "",
      "",
      "500",
      "",
      "",
      "",
      "",
      "",
      "",
      "Lieferkette, Bericht, Akkreditierung",
      "ja",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "6",
      "ProdSG",
      "BGBl. I S. 3146, 3147",
      "Gesetz über die Bereitstellung von Produkten auf dem Markt (Produktsicherheitsgesetz - ProdSG)",
      "Gesetz",
      "Gesetz",
      "Dieses Gesetz ist anzuwenden, wenn im Rahmen einer Geschäftstätigkeit Produkte auf dem Markt bereitgestellt, ausgestellt oder erstmals verwendet werden",
      "",
      "https://www.gesetze-im-internet.de/prodsg_2021/ProdSG.pdf",
      "",
      "",
      "x",
      "",
      "2021-07-27",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktsicherheit, Produktentwicklung, Nutzung",
      "ja",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "6.1",
      "AllgProdS (Richtlinie)",
      "2001/95/EG",
      "Richtlinie Allgemeine Produktsicherheit",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Die Richtlinie über die allgemeine Produktsicherheit (2001/95/EG) ist eine EU-Richtlinie, die darauf abzielt, die Sicherheit von Verbraucherprodukten auf dem europäischen Markt zu gewährleisten. Sie gilt für eine breite Palette von Konsumgütern, einschließlich Spielzeug, Elektrogeräte, Möbel, Kosmetika und mehr. Das Hauptziel dieser Richtlinie besteht darin, das Risiko von Verletzungen, Gesundheitsschäden und anderen Gefahren für Verbraucher zu minimieren, die Produkte verwenden oder damit in Kontakt kommen.\r\n\r\nDie Richtlinie über die allgemeine Produktsicherheit legt Anforderungen an Hersteller und Importeure fest, sicherzustellen, dass die von ihnen in Verkehr gebrachten Produkte sicher sind. Dies umfasst die Verpflichtung, Risikobewertungen durchzuführen, erforderliche Sicherheitsmaßnahmen zu ergreifen, klare Kennzeichnungen und Warnhinweise anzubringen und im Bedarfsfall Rückrufaktionen durchzuführen, wenn festgestellt wird, dass ein Produkt nicht sicher ist.\r\n\r\nDurch die Umsetzung dieser Richtlinie sollen Verbraucher vor unsicheren Produkten geschützt und ein hohes Maß an Produktsicherheit im europäischen Markt gewährleistet werden",
      "",
      "https://eur-lex.europa.eu/eli/dir/2001/95",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktsicherheit, Produktentwicklung, Nutzung",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "6.2",
      "MaschRich 2006 (Richtlinie)",
      "2006/42/EG",
      "Maschinenrichtlinie",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Die Maschinenrichtlinie (2006/42/EG) ist eine EU-Richtlinie, die Sicherheits- und Gesundheitsanforderungen für Maschinen festlegt, die innerhalb des Europäischen Wirtschaftsraums (EWR) in Verkehr gebracht werden. Ziel ist es, einen hohen Schutz für Personen zu gewährleisten, die solche Maschinen bedienen, warten oder instand halten. Die Richtlinie legt grundlegende Prinzipien fest, die Hersteller bei der Gestaltung, Herstellung und Inverkehrbringung von Maschinen berücksichtigen müssen, um potenzielle Risiken zu minimieren. Dazu gehören Aspekte wie Sicherheit, ergonomisches Design, Kennzeichnung und Informationspflichten für Benutzer. Die Maschinenrichtlinie zielt darauf ab, einheitliche Standards für Maschinensicherheit in der gesamten EU zu etablieren und somit den freien Warenverkehr zu erleichtern.",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32006L0042",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktsicherheit, Produktentwicklung, Nutzung",
      "ja",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "6.3",
      "Niederspannungsrichtlinie (Richtlinie)",
      "2014/35/EU",
      "Niederspannungsrichtlinie 2014/35/EU",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktsicherheit, Produktentwicklung, Nutzung, Nierspannung",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "6.4",
      "Spielzeugrichtlinie (Richtlinie)",
      "2009/48/EG",
      "Spielzeug-Richtlinie 2009/48/EG",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktsicherheit, Produktentwicklung, Nutzung, Spielzeug",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "7",
      "EVPG",
      "BGBl. I S. 258",
      "Energieverbrauchsrelevante-Produkte-Gesetz (EVPG)",
      "Gesetz",
      "Gesetz",
      "Das Energieverbrauchsrelevante-Produkte-Gesetz setzt die EU-Ökodesignrichtlinie in deutsches Recht um und ist am 7. März 2008 in Kraft getreten. Die Frist zur Umsetzung der Richtlinie war auf den 11. August 2007 bestimmt. § 10 EVPG bestimmt als beauftragte Stelle die Bundesanstalt für Materialforschung und -prüfung",
      "",
      "https://www.bmwk.de/Redaktion/DE/Gesetze/Energie/evpg.html",
      "",
      "",
      "x",
      "",
      "2011-11-25",
      "",
      "2020-06-19",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "Kennzeichnung",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "7.1",
      "Eco Design 2009 (Richtlinie)",
      "2009125EG",
      "Berücksichtung Produktgruppenspezifischer Ökodesign-Anforderungen aus der Öko Design Richtlinie 2009/125/EG",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Die Richtlinie 2009/125/EG, auch bekannt als Ökodesign-Richtlinie, legt Anforderungen für umweltgerechtes Produktdesign und Energieeffizienz von verschiedenen Produkten in der Europäischen Union fest. Im Kontext von Polyethylen (PE) bezieht sich die Richtlinie auf Anforderungen, die dazu dienen, umweltfreundliche Aspekte bei der Herstellung und Nutzung von PE-Produkten zu berücksichtigen. Dies kann die Reduzierung von Energieverbrauch, Ressourceneffizienz, Langlebigkeit und Recyclingfähigkeit von PE-Produkten einschließen, um deren Umweltauswirkungen zu minimieren und einen nachhaltigen Umgang mit Kunststoffen zu fördern.",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/ALL/?uri=celex:32009L0125",
      "",
      "x",
      "",
      "",
      "2009-11-20",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "8",
      "EnVKG",
      "BGBl. I S. 1070",
      "Energieverbrauchs-kennzeichnungsgesetz (EnVKG)",
      "Gesetz",
      "Gesetz",
      "Gesetz zur Kennzeichnung von energieverbrauchsrelevanten Produkten, Kraftfahrzeugen und Reifen mit Angaben über den Verbrauch an Energie und an anderen wichtigen Ressourcen (Energieverbrauchskennzeichnungsgesetz - EnVKG",
      "",
      "https://www.gesetze-im-internet.de/envkg_2012/BJNR107010012.html#BJNR107010012BJNG000100118",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Kennzeichnung",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "8.1",
      "EnVKV (Verordnung)",
      "BGBl. I S. 2616",
      "Energieverbrauchs-kennzeichnungsverordnung (EnVKV)",
      "Interpretierte Anforderung",
      "Verordnung",
      "Die Energieverbrauchskennzeichnungsverordnung (EnVKV) ist eine deutsche Verordnung, die auf der Grundlage der EU-Richtlinie 2010/30/EU erlassen wurde. Sie hat das Ziel, Verbrauchern klare und vergleichbare Informationen über den Energieverbrauch von bestimmten energieverbrauchsrelevanten Produkten zu bieten. Die EnVKV betrifft Produkte wie Haushaltsgeräte, Beleuchtung, Heizungsanlagen, Klimageräte und Fahrzeuge.\r\n\r\nDie Verordnung legt fest, dass bestimmte Produkte mit einem Energieetikett versehen werden müssen, das Informationen über den Energieverbrauch und die Energieeffizienz des Produkts liefert. Dieses Etikett ermöglicht es Verbrauchern, Produkte leicht miteinander zu vergleichen und energieeffiziente Optionen zu identifizieren. Das Etikett enthält normalerweise eine Skala von A (sehr effizient) bis G (weniger effizient), wobei A oft in weitere Stufen unterteilt ist, um feinere Unterschiede darzustellen.\r\n\r\nDie Energieverbrauchskennzeichnungsverordnung trägt zur Förderung energieeffizienter Produkte bei und unterstützt die Verbraucher dabei, fundierte Entscheidungen zu treffen, die sowohl ihre individuellen Bedürfnisse als auch Umwelt- und Kostengesichtspunkte berücksichtigen",
      "",
      "https://www.gesetze-im-internet.de/envkv/BJNR261600997.html",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Kennzeichnung",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "8.2",
      "EWR (Verordnung)",
      "2017/1369/EU",
      "Festlegung eines Rahmens für die Energieverbrauchskennzeichnung und zur Aufhebung der Richtlinie 2010/30/EU",
      "Interpretierte Anforderung",
      "Verordnung",
      "setting a framework for energy labelling and repealing Directive 2010/30/EU",
      "",
      "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32017R1369",
      "",
      "x",
      "",
      "",
      "2017-07-04",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Kennzeichnung",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "8.3",
      "Eco Design 2009 (Richtlinie)",
      "2009125EG",
      "Berücksichtung Produktgruppenspezifischer Ökodesign-Anforderungen aus der Öko Design Richtlinie 2009/125/EG",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Die Richtlinie 2009/125/EG, auch bekannt als Ökodesign-Richtlinie, legt Anforderungen für umweltgerechtes Produktdesign und Energieeffizienz von verschiedenen Produkten in der Europäischen Union fest. Im Kontext von Polyethylen (PE) bezieht sich die Richtlinie auf Anforderungen, die dazu dienen, umweltfreundliche Aspekte bei der Herstellung und Nutzung von PE-Produkten zu berücksichtigen. Dies kann die Reduzierung von Energieverbrauch, Ressourceneffizienz, Langlebigkeit und Recyclingfähigkeit von PE-Produkten einschließen, um deren Umweltauswirkungen zu minimieren und einen nachhaltigen Umgang mit Kunststoffen zu fördern.",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/ALL/?uri=celex:32009L0125",
      "",
      "x",
      "",
      "",
      "2009-11-20",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Produktentwcklung",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "9",
      "EVPGV",
      "BGBl. I S. 3221",
      "Verordnung zur Durchführung des Gesetzes über die umweltgerechte Gestaltung energieverbrauchsrelevanter Produkte (EVPGV)",
      "Gesetz",
      "Gesetz",
      "Die \"Verordnung zur Durchführung des Gesetzes über die umweltgerechte Gestaltung energieverbrauchsrelevanter Produkte\" (EVPGV) ist eine deutsche Verordnung, die im Rahmen des Gesetzes über die umweltgerechte Gestaltung energieverbrauchsrelevanter Produkte (Energieverbrauchsrelevante-Produkte-Gesetz - EVPG) erlassen wurde. Sie dient der Umsetzung der Anforderungen der europäischen Ökodesign-Richtlinie (2009/125/EG) in nationales deutsches Recht.\r\n\r\nDas Energieverbrauchsrelevante-Produkte-Gesetz (EVPG) und die zugehörige Durchführungsverordnung (EVPGV) zielen darauf ab, die Energieeffizienz von Produkten zu verbessern und somit zur Verringerung des Energieverbrauchs und der Treibhausgasemissionen beizutragen. Die Verordnung legt spezifische Anforderungen für die umweltgerechte Gestaltung bestimmter energieverbrauchsrelevanter Produkte fest.\r\n\r\nDie EVPGV legt fest, welche Produktkategorien unter das Gesetz fallen und welche Anforderungen für die umweltgerechte Gestaltung dieser Produkte gelten. Dies kann technische Anforderungen, Energieeffizienzklassen, Kennzeichnungspflichten und andere Maßnahmen zur Förderung der Energieeffizienz beinhalten.\r\n\r\nDie EVPGV ist Teil der Bemühungen Deutschlands und der Europäischen Union, die Energieeffizienz zu steigern, nachhaltige Produktions- und Verbrauchsmuster zu fördern und damit einen Beitrag zur Erreichung der Klima- und Umweltschutzziele zu leisten. Wenn Sie spezifische Informationen zur Verordnung benötigen, empfehle ich Ihnen, sich an offizielle rechtliche Quellen oder Behörden zu wenden, die mit ihrer Umsetzung befasst sind.",
      "",
      "https://www.gesetze-im-internet.de/evpgv/BJNR322110013.html",
      "",
      "",
      "x",
      "",
      "2013-08-18",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Ökodesign",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "9.1",
      "Anforderung EVPGV (Richtlinie)",
      "2009125EG",
      "Berücksichtung Produktgruppenspezifischer Ökodesign-Anforderungen aus der Öko Design Richtlinie 2009/125/EG",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Die Richtlinie 2009/125/EG, auch bekannt als Ökodesign-Richtlinie, legt Anforderungen für umweltgerechtes Produktdesign und Energieeffizienz von verschiedenen Produkten in der Europäischen Union fest. Im Kontext von Polyethylen (PE) bezieht sich die Richtlinie auf Anforderungen, die dazu dienen, umweltfreundliche Aspekte bei der Herstellung und Nutzung von PE-Produkten zu berücksichtigen. Dies kann die Reduzierung von Energieverbrauch, Ressourceneffizienz, Langlebigkeit und Recyclingfähigkeit von PE-Produkten einschließen, um deren Umweltauswirkungen zu minimieren und einen nachhaltigen Umgang mit Kunststoffen zu fördern.",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/ALL/?uri=celex:32009L0125",
      "",
      "x",
      "",
      "",
      "2009-11-20",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Ökodesign, Produktgestaltung, Produktentwicklung",
      "ja",
      "45163",
      "",
      "x",
      "Produktgestaltung",
      "x"
    ],
    [
      "10",
      "BDSG",
      "",
      "Bundesdatenschutzgesetz (BDSG)",
      "Gesetz",
      "Gesetz",
      "Gesetz zur Anpassung des Datenschutzrechts an die\r\nVerordnung (EU) 2016/679 und zur Umsetzung der Richtlinie (EU) 2016/680 (Datenschutz-Anpassungs- und -Umsetzungsgesetz EU – DSAnpUG-EU)",
      "",
      "https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl117s2097.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl117s2097.pdf%27%5D__1692949502060",
      "",
      "",
      "x",
      "",
      "2017-06-30",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "x",
      "Kundendaten",
      "x"
    ],
    [
      "10.1",
      "Anforderung BDSG (Verordnung)",
      "2016/679/EU",
      "Datenschutzgrundverordnung (DSGVO)",
      "Interpretierte Anforderung",
      "Verordnung",
      "Die Datenschutz-Grundverordnung (DSGVO) ist eine EU-Verordnung, die am 25. Mai 2018 in Kraft getreten ist. Sie regelt den Schutz personenbezogener Daten und die Privatsphäre von Personen innerhalb der Europäischen Union (EU). Die DSGVO hat das Ziel, einheitliche Standards für den Umgang mit personenbezogenen Daten zu etablieren und die Rechte der betroffenen Personen zu stärken.\r\n\r\nDie DSGVO enthält Regelungen und Vorgaben für Unternehmen, Organisationen und Behörden, die personenbezogene Daten verarbeiten. Dazu gehören Aspekte wie Einwilligung der betroffenen Person, Datenschutzrechte, Informationspflichten, Datenübertragbarkeit, Datensicherheit, Datenschutz-Folgenabschätzungen und die Meldepflicht bei Datenschutzverletzungen. Unternehmen, die personenbezogene Daten verarbeiten, müssen sicherstellen, dass ihre Datenschutzpraktiken den Anforderungen der DSGVO entsprechen.\r\n\r\nDie DSGVO zielt darauf ab, das Recht auf Privatsphäre und den Schutz personenbezogener Daten in einer zunehmend digitalisierten Welt zu gewährleisten. Sie gilt für Unternehmen und Organisationen, die innerhalb der EU ansässig sind, sowie für solche, die personenbezogene Daten von EU-Bürgern verarbeiten, unabhängig davon, wo sich die Verarbeitung physisch befindet. Verstöße gegen die DSGVO können zu erheblichen Geldstrafen führen.\r\n\r\n\r\n\r\n\r\n",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/ALL/?uri=celex%3A32016R0679",
      "",
      "x",
      "",
      "",
      "2018-05-25",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Datenschutz",
      "nein",
      "45163",
      "",
      "x",
      "Kundendaten",
      "x"
    ],
    [
      "11",
      "GDDM",
      "",
      "Gesetz über digitale Dienste und Märkte zur Umsetzung von DAS und DMA in Abgrenzung zum GWB-Digitalisierungsgesetzes",
      "Gesetz",
      "Gesetz",
      "",
      "",
      "https://www.bundestag.de/resource/blob/880748/856d83cb24c61822c508aa47f27e18e7/WD-7-114-21-PE-6-067-21-pdf-data.pdf",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "11.1",
      "Anforderung GDDM (Verordnung)",
      "2022/2065/EU",
      "Digital Service Act EU",
      "Interpretierte Anforderung",
      "Verordnung",
      "",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32022R2065&from=en",
      "",
      "x",
      "",
      "",
      "2022-11-16",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Datenschutz",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "11.2",
      "Anforderung GDDM (Verordnung)",
      "2022/1925/EU",
      "Digital Markets Act EU",
      "Interpretierte Anforderung",
      "Verordnung",
      "",
      "",
      "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv%3AOJ.L_.2022.265.01.0001.01.ENG&toc=OJ%3AL%3A2022%3A265%3ATOC",
      "",
      "x",
      "",
      "",
      "2022-09-14",
      "ja",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Datenschutz",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "12",
      "KSG",
      "KSG",
      "Bundes-Klimaschutzgesetz",
      "Gesetz",
      "Gesetz",
      "Das Bundes-Klimaschutzgesetz ist ein deutsches Gesetz, das am 18. Dezember 2019 verabschiedet wurde und am 1. Januar 2020 in Kraft getreten ist. Ziel des Gesetzes ist es, die nationalen Klimaschutzziele der Bundesrepublik Deutschland zu konkretisieren und rechtlich verbindlich festzulegen. Es legt Maßnahmen und Instrumente zur Reduzierung der Treibhausgasemissionen fest, um die Klimaziele des Pariser Abkommens zu erreichen.\r\n\r\nDas Bundes-Klimaschutzgesetz legt verbindliche Reduktionsziele für die einzelnen Wirtschaftssektoren bis 2030 fest und definiert die jährlichen Minderungspfade. Es sieht auch vor, dass, wenn diese Minderungspfade nicht erreicht werden, zusätzliche Maßnahmen ergriffen werden müssen, um die Ziele zu erreichen. Das Gesetz enthält auch Bestimmungen zur Überwachung, Berichterstattung und Bewertung der Umsetzung der Klimaschutzmaßnahmen.\r\n\r\nEine wichtige Komponente des Gesetzes ist die Einführung eines nationalen Emissionshandelssystems für Sektoren, die nicht bereits im EU-Emissionshandelssystem (ETS) abgedeckt sind. Dieses System betrifft hauptsächlich den Verkehr und die Gebäudewirtschaft und sieht vor, dass Unternehmen Emissionszertifikate erwerben müssen, um ihre Emissionen abzudecken.\r\n\r\nDas Bundes-Klimaschutzgesetz ist ein bedeutender Schritt, um Deutschland auf einen kohlenstoffarmen Pfad zu bringen und die Klimaziele des Landes zu erreichen. Es zielt darauf ab, den Übergang zu einer nachhaltigen, emissionsarmen Wirtschaft zu fördern und die Verpflichtungen des Landes im internationalen Klimaschutz zu erfüllen.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "2020-01-01",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Zielsystem, Ökodesign",
      "nein",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "12.1",
      "Anforderung KSG (Verordnung)",
      "EUGD",
      "European Green Deal",
      "Interpretierte Anforderung",
      "Verordnung",
      "Der Europäische Green Deal, auf Englisch \"European Green Deal\", ist eine politische Initiative und ein umfassendes Maßnahmenpaket der Europäischen Union (EU), das im Dezember 2019 von der Europäischen Kommission vorgestellt wurde. Ziel des Europäischen Green Deals ist es, Europa bis 2050 zum ersten klimaneutralen Kontinent zu machen und dabei sowohl ökologische als auch wirtschaftliche Nachhaltigkeit zu fördern.\r\n\r\nDer Green Deal hat eine breite Palette von Zielen und Maßnahmen, die verschiedene Bereiche der Politik und Wirtschaft abdecken:\r\n\r\nKlimaneutralität: Bis 2050 sollen die EU-weiten Netto-Treibhausgasemissionen auf null reduziert werden, um den Klimawandel einzudämmen.\r\n\r\nEnergieeffizienz und erneuerbare Energien: Die Energieeffizienz soll gesteigert und der Anteil erneuerbarer Energien am Energiemix erhöht werden.\r\n\r\nUmwelt- und Biodiversitätsschutz: Der Erhalt der Biodiversität und der Schutz der Umwelt stehen im Fokus, unter anderem durch Wiederherstellung von Ökosystemen und nachhaltige Landwirtschaft.\r\n\r\nKreislaufwirtschaft und Ressourceneffizienz: Die EU will eine nachhaltige Kreislaufwirtschaft fördern, um Ressourcen besser zu nutzen und Abfälle zu reduzieren.\r\n\r\nNachhaltige Mobilität: Förderung von emissionsfreien Verkehrsoptionen und Ausbau der nachhaltigen Verkehrsinfrastruktur.\r\n\r\nBauwesen und Renovierung: Die Effizienz von Gebäuden soll gesteigert und die Renovierung von Gebäuden nachhaltiger gestaltet werden.\r\n\r\nLandwirtschaft und Lebensmittel: Förderung einer nachhaltigen Landwirtschaft und Stärkung der Lebensmittelsicherheit.\r\n\r\nDer Europäische Green Deal ist nicht nur auf Umwelt- und Klimaaspekte ausgerichtet, sondern zielt auch darauf ab, Wachstum, Innovation und Arbeitsplätze in Europa zu fördern. Er soll einen umfassenden Wandel in der Wirtschaft und Gesellschaft unterstützen und Europa weltweit als Vorreiter im Bereich nachhaltige Entwicklung positionieren. Der Green Deal beeinflusst eine Vielzahl von Politikbereichen und wird in den kommenden Jahren eine wichtige Rolle in der EU-Politik spielen",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Zielsystem, Strategie, Strategische Aus",
      "nein",
      "45163",
      "",
      "x",
      "Strategische Ausrichtung",
      "x"
    ],
    [
      "13",
      "EWKFondsF",
      "BGBl. 2023 I Nr. 124",
      "Einwegkunststofffondsgesetz (EWKFondsG)",
      "Gesetz",
      "Gesetz",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "2022-11-02",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "13.1",
      "Anforderung EWKFondsF (Richtlinie)",
      "2019/904/EU",
      "EU-Einwegkunststoffrichtlinie",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Richtlinie zur Verringerung der Auswirkungen bestimmter Kunststoffprodukte auf die Umwelt",
      "",
      "https://eur-lex.europa.eu/eli/dir/2019/904/oj",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Ökodesign, Kreislauffähigkeit, Verpackung, Kennzeichnung",
      "ja",
      "45163",
      "",
      "x",
      "Wegwerfartikel",
      "x"
    ],
    [
      "14",
      "VerpackG",
      "BGBl. 2023 I Nr. 124",
      "Verpackungsgesetz",
      "Gesetz",
      "Gesetz",
      "Entwurf eines Gesetzes zur Umsetzung von Vorgaben der\r\nEinwegkunststoffrichtlinie und der Abfallrahmenrichtlinie\r\nim Verpackungsgesetz und in anderen Gesetzen",
      "",
      "https://www.bmuv.de/gesetz/entwurf-eines-gesetzes-zur-umsetzung-von-vorgaben-der-einwegkunststoffrichtlinie-und-der-abfallrahmenrichtlinie-im-verpackungsgesetz-und-in-anderen-gesetzen",
      "",
      "",
      "x",
      "",
      "2021-03-21",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "Ökodesign, Kreislauffähigkeit, Verpackung, Kennzeichnung, Versand",
      "ja",
      "45163",
      "",
      "x",
      "Versand",
      "x"
    ],
    [
      "14.1",
      "Anforderung VerpackG (Richtlinie)",
      "2019/904/EU",
      "Berücksichtigun der EU-Richtlinie 2019/904/EU: Verringerung der Auswirkungen bestimmter Kunststoffprodukte auf die Umwelt ",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Verringerung der Auswirkungen bestimmter Kunststoffprodukte auf die Umwelt ",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "Ökodesign, Kreislauffähigkeit, Verpackung, Kennzeichnung, Versand",
      "",
      "45163",
      "",
      "x",
      "Verpackungen",
      "x"
    ],
    [
      "14.2",
      "Anforderung VerpackG (Richtlinie)",
      "2015/720/EU",
      "Berücksichtigun der EU-Richtlinie 2015/720/EU: \"Richtlinie über Verpackungen und Verpackungsabfälle\"",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Die \"Richtlinie über Verpackungen und Verpackungsabfälle\" ist eine EU-Richtlinie, die die ordnungsgemäße Bewirtschaftung von Verpackungen und den dazugehörigen Abfällen regelt. Die Richtlinie trägt die Nummer 94/62/EG und wurde am 20. Dezember 1994 verabschiedet. Sie wurde inzwischen durch die Richtlinie (EU) 2018/852 ersetzt.\r\n\r\nDie Zielsetzungen der Verpackungsrichtlinie waren unter anderem:\r\n\r\nVermeidung von Abfällen: Förderung der Vermeidung von Verpackungsabfällen durch umweltfreundliches Verpackungsdesign und die Verwendung von wiederverwendbaren oder recyclebaren Materialien.\r\n\r\nFörderung von Recycling und Wiederverwendung: Förderung von Recycling und Wiederverwendung von Verpackungsabfällen, um Ressourceneffizienz und Umweltschutz zu verbessern.\r\n\r\nMinimierung von Umweltauswirkungen: Reduzierung der Umweltauswirkungen von Verpackungsabfällen, insbesondere von problematischen Abfällen.\r\n\r\nKennzeichnung von Verpackungen: Einführung von Systemen zur Kennzeichnung von Verpackungen zur Identifizierung von Materialien und zur Unterstützung der ordnungsgemäßen Sortierung und Recycling.\r\n\r\nErweiterter Herstellerverantwortung: Förderung der Hersteller, die Verantwortung für die umweltgerechte Entsorgung ihrer Verpackungen zu übernehmen.\r\n\r\nDie Verpackungsrichtlinie legt fest, dass die Mitgliedstaaten der EU nationale Regelungen erlassen sollen, um die Ziele der Richtlinie zu erreichen. Sie hat zur Einführung verschiedener Maßnahmen in den Mitgliedstaaten geführt, wie etwa Recyclingquoten, Pfandsysteme und andere Anreize für eine nachhaltigere Verpackung und Verpackungsabfallbewirtschaftung",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/TXT/PDF/?uri=CELEX:32015L0720",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "Ökodesign, Kreislauffähigkeit, Verpackung",
      "ja",
      "45163",
      "",
      "x",
      "Verpackungen",
      "x"
    ],
    [
      "14.3",
      "Anforderung VerpackG (Gesetz)",
      "BGBl. 2023 I Nr. 124",
      "Aus Verpackungsgesetz: Eintragung im Verpackungsregister",
      "Interpretierte Anforderung",
      "Gesetz",
      "Europaweit gilt für Verpackungen, dass der Hersteller eines Produkts auch für die Verpackung die Produktverantwortung im Sinne von Vermeidung, Wiederverwendung und Verwertung übernimmt. Die Umsetzung in Deutschland erfolgt über das Verpackungsgesetz (VerpackG).\r\nDie Zentrale Stelle Verpackungsregister übernimmt in diesem Zusammenhang die Aufgabe, die Produktverantwortlichen zu registrieren und damit öffentlich zu machen und über weitere Aufgaben (z. B. Datenmeldung) für Transparenz und Rechtsklarheit zu sorgen. Die weiteren ökologischen Ziele, wie u. a. die Erfüllung der Recyclingquoten und die finanzielle Förderung von nachhaltigeren Verpackungen, werden durch die Zentrale Stelle Verpackungsregister überwacht.",
      "",
      "https://www.verpackungsregister.org/",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "14.4",
      "Anforderung VerpackG (Gesetz)",
      "BGBl. 2023 I Nr. 124",
      "Aus Verpackungsgesetz: Einwegkunststofffgetränkeflaschen",
      "Interpretierte Anforderung",
      "Gesetz",
      "Von den kalenderjährlich erstmals in Verkehr gebrachten Einwegkunststoffgetränkeflaschen sind ab dem 1. Januar 2025 mindestens 77 Masseprozent und ab dem 1. Januar 2029 mindestens 90 Masseprozent zum Zweck des Recyclings getrennt zu sammeln; ausgenommen davon sind Einwegkunststoffgetränkeflaschen nach § 30a Absatz 3.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "15",
      "Kreislaufwirtschaftsgesetz",
      "KrWG",
      "Gesetz zur Förderung der Kreislaufwirtschaft und Sicherung der umweltverträglichen Beseitigung von Abfällen",
      "Gesetz",
      "Gesetz",
      "Dieses Gesetz setzt EU-Richtlinien zur Abfallwirtschaft um und legt Ziele für die Abfallvermeidung und -verwertung fest.",
      "",
      "https://www.gesetze-im-internet.de/krwg/",
      "",
      "",
      "x",
      "",
      "2012-02-24",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "Ökodesign, Beschaffung, Nutzung, Reyxcling, Abfall, Kreislauffähigkeit, Verpackung",
      "",
      "45163",
      "",
      "x",
      "Kreislauffähigkeit und Nutzung im Fokus",
      "x"
    ],
    [
      "15.1",
      "Anforderung Kreislaufwirtschaftsgesetz (Gesetz)",
      "KrWG",
      "Produktverantwortung und Produktgestaltung beim KrWG",
      "Interpretierte Anforderung",
      "Gesetz",
      "Zitiert \"Wer Erzeugnisse entwickelt, herstellt, be- oder verarbeitet oder vertreibt, trägt zur Erfüllung der Ziele der Kreislaufwirtschaft die Produktverantwortung. Erzeugnisse sind möglichst so zu gestalten, dass bei ihrer Herstellung und ihrem Gebrauch das Entstehen von Abfällen vermindert wird und sichergestellt ist, dass die nach ihrem Gebrauch entstandenen Abfälle umweltverträglich verwertet oder beseitigt werden\"",
      "",
      "https://www.gesetze-im-internet.de/krwg/",
      "",
      "",
      "x",
      "",
      "2012-02-24",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "Ökodesign, Beschaffung, Nutzung, Reyxcling, Abfall, Kreislauffähigkeit, Verpackung",
      "",
      "45163",
      "",
      "x",
      "Beschaffunganforderungn",
      "x"
    ],
    [
      "15.2",
      "Anforderung Kreislaufwirtschaftsgesetz (Gesetz)",
      "KrWG",
      "Produktverantwortung und Vertrieb beim KrWG",
      "Interpretierte Anforderung",
      "Gesetz",
      "Beim Vertrieb der Erzeugnisse ist dafür zu sorgen, dass deren Gebrauchstauglichkeit erhalten bleibt und diese nicht zu Abfall werden.",
      "",
      "https://www.gesetze-im-internet.de/krwg/",
      "",
      "",
      "x",
      "",
      "2012-02-24",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "Ökodesign, Beschaffung, Nutzung, Reyxcling, Abfall, Kreislauffähigkeit, Verpackung",
      "",
      "45163",
      "",
      "x",
      "Großes Thema bei Geschenken",
      "x"
    ],
    [
      "15.3",
      "Anforderung Kreislaufwirtschaftsgesetz (Richtlinie)",
      "200898EG",
      "Richtlinie über Abfälle und zur Aufhebung bestimmter Richtlinien (Text von Bedeutung für den EWR)",
      "Interpretierte Anforderung",
      "Richtlinie",
      "Die \"Richtlinie über Abfälle und zur Aufhebung bestimmter Richtlinien\" ist eine EU-Richtlinie, die oft als \"Abfallrahmenrichtlinie\" bezeichnet wird. Die Richtlinie trägt die Nummer 2008/98/EG und wurde am 19. November 2008 verabschiedet. Sie legt grundlegende Regelungen und Prinzipien für die Bewirtschaftung von Abfällen in der Europäischen Union fest. Sie soll einen Beitrag zur Förderung einer nachhaltigen Abfallwirtschaft leisten und Umweltbelastungen durch Abfälle minimieren.\r\n\r\nDie Abfallrahmenrichtlinie umfasst verschiedene Aspekte:\r\n\r\nHierarchie der Abfallbewirtschaftung: Die Richtlinie legt die Abfallhierarchie fest, die die bevorzugten Optionen für die Bewirtschaftung von Abfällen in folgender Reihenfolge vorgibt: Vermeidung, Vorbereitung zur Wiederverwendung, Recycling, sonstige Verwertung (z.B. energetische Verwertung) und Beseitigung.\r\n\r\nGetrennte Sammlung: Die Richtlinie fordert die Förderung der getrennten Sammlung von Abfällen, um eine effiziente Verwertung und Recycling zu ermöglichen.\r\n\r\nAbfallbegriff: Die Definition von Abfällen wird klar definiert, um sicherzustellen, dass die Regelungen auf alle relevanten Materialströme anwendbar sind.\r\n\r\nVerantwortung des Erzeugers: Die Richtlinie betont die Verantwortung der Hersteller für die umweltgerechte Entsorgung ihrer Produkte und fördert Konzepte wie erweiterte Herstellerverantwortung.\r\n\r\nBeseitigung von Abfällen: Die Richtlinie enthält Regelungen für die Beseitigung von Abfällen, insbesondere für Abfälle, die nicht recycelbar oder verwertbar sind.\r\n\r\nBerichterstattung und Überwachung: Die Mitgliedstaaten werden aufgefordert, Abfallbewirtschaftungspläne zu entwickeln und zu überwachen, um sicherzustellen, dass die Ziele der Richtlinie erreicht werden.\r\n\r\nDie Abfallrahmenrichtlinie ist ein wichtiger rechtlicher Rahmen für die Abfallwirtschaft in der EU und hat zum Ziel, Ressourceneffizienz, Umweltschutz und Kreislaufwirtschaft zu fördern. Sie wurde in den Mitgliedstaaten der Europäischen Union in nationales Recht umgesetzt.",
      "",
      "https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=celex:32008L0098",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "Alle",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "Ökodesign, Beschaffung, Nutzung, Reyxcling, Abfall, Kreislauffähigkeit, Verpackung",
      "ja",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "16",
      "BattG",
      "",
      "Batteriegesetz (BattG)",
      "Gesetz",
      "Gesetz",
      "Das BattG setzt die europäische Batterie­richtlinie 2006/66/EG in deutsches Recht um. Es regelt das Inverkehr­bringen, die Rück­nahme und die umwelt­verträgliche Entsorgung von Batterien und Akku­mulatoren. Das Gesetz trat erstmalig im Jahr 2009 in Kraft und wurde 2021 aktualisiert (BattG2)",
      "",
      "https://www.gesetze-im-internet.de/battg/BJNR158210009.html",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "16.1",
      "Anforderung BattG (Richtlinie)",
      "",
      "umsetzung der EU Batterierichtlinie 2006/66/EG",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "17",
      "ChemG",
      "",
      "Chemikaliengesetz (ChemG)",
      "Gesetz",
      "Gesetz",
      "",
      "",
      "https://www.gesetze-im-internet.de/chemg/",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "17.1",
      "Anforderung ChemG (Verordnung)",
      "BGBl. I S. 3115",
      "Gefahrstoffverordnung (GefStoffV)",
      "Interpretierte Anforderung",
      "Verordnung",
      "Verordnung zum Schutz vor Gefahrstoffen*) (Gefahrstoffverordnung - GefStoffV)",
      "",
      "https://www.gesetze-im-internet.de/gefstoffv_2010/",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "18",
      "ARSG",
      "",
      "Arbeitsschutzgesetz (ArbSchG)",
      "Gesetz",
      "Gesetz",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "18.1",
      "Anforderung ARSG (Verordnung)",
      "",
      "Betriebssicherheitsverordnung (BetrSichV)",
      "Interpretierte Anforderung",
      "Verordnung",
      "BetrSichV setzt die EU - Richtlinie 2009/104/ EG über Mindestvorschriften für Sicherheit und Gesundheitsschutz bei Benutzung von Arbeitsmitteln durch Arbeitnehmer bei der Arbeit in deutsches Recht um und ist dazu auf das Arbeitsschutzgesetz gestützt.",
      "",
      "https://www.gesetze-im-internet.de/bimschg/",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "gültig",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "45163",
      "",
      "",
      "",
      "x"
    ],
    [
      "18.2",
      "Anforderung ARSG (Verordnung)",
      "",
      "Arbeitsstättenverordnung (ArbStättV)",
      "Interpretierte Anforderung",
      "Verordnung",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "18.3",
      "Anforderung ARSG (Verordnung)",
      "",
      "Verordnung zum Schutz der Beschäftigten vor Gefährdungen durch Lärm und Vibrationen\" (LärmVibrationsArbSchV)",
      "Interpretierte Anforderung",
      "Verordnung",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "18.4",
      "Anforderung ARSG (Verordnung)",
      "",
      "Lastenhandhabungsverordnung (LasthandhabV)",
      "Interpretierte Anforderung",
      "Verordnung",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "18.5",
      "Anforderung ARSG (Verordnung)",
      "",
      "Unfallverhütungsvorschriften",
      "Interpretierte Anforderung",
      "Verordnung",
      "Maßnahmen, Einrichtungen und Anordnungen zur Verhütung von Unfällen am Arbeitsplatz, Berufskrankheiten oder Gesundheitseinschränkungen,\r\nAnweisungen zum Verhalten der Beschäftigten zur Vermeidung von Unfällen,\r\narbeitsmedizinische Maßnahmen und Voraussetzungen, die der durchführende Arzt erfüllen muss,\r\ndie Sicherstellung der Ersten Hilfe\r\nund die Zahl der Sicherheitsbeauftragten unter Berücksichtigung der Verhältnisse im Unternehmen.",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "18.6",
      "Anforderung ARSG ",
      "",
      "Gefährdungsbeurteilung",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "19",
      "BImSchG",
      "",
      "Bundes-Immissionsschutzgesetz (BImSchG)",
      "Gesetz",
      "Gesetz",
      "",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "19.1",
      "Anforderung BImSchG (Richtlinie)",
      "2002/49/EG",
      "Richtlinie über die Bewertung und die Bekämpfung von Umgebungslärm. RL 2002/49/EG",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "19.2",
      "Anforderung BImSchG (Richtlinie)",
      "2001/81/EG",
      "Richtlinie über nationale Emissionshöchstmengen für bestimmte Luftschadstoffe. RL 2001/81/EG",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "19.3",
      "Anforderung BImSchG (Richtlinie)",
      "2008/50/EG",
      "Luftqualitätsrichtlinie. RL 2008/50/EG",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "19.4",
      "Anforderung BImSchG (Richtlinie)",
      "2010/75/EU",
      "Industrieemissionsrichtlinie. IE-RL, 2010/75/EU",
      "Interpretierte Anforderung",
      "Richtlinie",
      "",
      "",
      "",
      "",
      "x",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ],
    [
      "19",
      "Patentgesetz",
      "",
      "Patentgesetz",
      "Gesetz",
      "Gesetz",
      "Der Schutz geistigen Eigentums ist für Unternehmen und besonders für Start-ups von unschätzbarem Wert. In Deutschland gilt der Grundsatz der Nachahmungsfreiheit. Ideen, Erfindungen, geistige Schöpfungen oder Designs sollen grundsätzlich der Nachahmung zugänglich sein, damit ein Fortschritt ermöglicht wird. Der Nachahmungsfreiheit ist nur da eine Grenze gesetzt, wo gewerbliche Schutzrechte (insbesondere Marke-Patent-Design) bestehen und ergänzend die Regelungen des unlauteren Wettbewerbs greifen.",
      "",
      "https://www.gesetze-im-internet.de/patg/",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "x"
    ]
  
    
  ];

  var tableHtml = '<thead><tr>';
  var headerRow = jsonData[0];
  for (var i = 0; i < headerRow.length; i++) {
    tableHtml += '<th>' + headerRow[i] + '<input type="checkbox" checked onchange="toggleColumn(i)">' + '</th>';
  }
  tableHtml += '</tr></thead>';

  tableHtml += '<tbody>';
  for (var j = 1; j < jsonData.length; j++) {
    var row = jsonData[j];
    tableHtml += '<tr>';
    for (var k = 0; k < row.length; k++) {
      tableHtml += '<td>' + row[k] + '</td>';
    }
    tableHtml += '</tr>';
  }
  tableHtml += '</tbody>';

  var tableElement = document.getElementById('excel-table');
  tableElement.innerHTML = tableHtml;
  tableData = jsonData; // Speichere die Tabellendaten

  const currentDate = new Date();
  $('tr').each(function() {
  const cellDate = new Date($(this).find('td:nth-child(11)').text());
  if (cellDate > currentDate) {
    $(this).addClass('future');
  }
  });

  $('tr').each(function() {
  if ($(this).find('td:nth-child(5)').text() === 'Interpretierte Anforderung') {
    $(this).addClass('ireq');
  }
  });

  $('tr').each(function() {
    if ($(this).find('td:nth-child(5)').text() === 'Lösungsorientierte Anforderung') {
      $(this).addClass('lreq');
    }
    });
}
